"""Audited target catalog for Ironclad A0 Act 1 combat coverage."""

from spirecomm.envs.vocab import IRONCLAD_CARD_IDS

IRONCLAD_CARDS = IRONCLAD_CARD_IDS

ACT1_NORMAL_ENCOUNTERS = (
    "CULTIST", "JAW_WORM", "TWO_LOUSE", "SMALL_SLIMES", "BLUE_SLAVER",
    "GREMLIN_GANG", "LOOTER", "LARGE_SLIME", "LOTS_OF_SLIMES",
    "EXORDIUM_THUGS", "EXORDIUM_WILDLIFE", "RED_SLAVER", "THREE_LOUSE",
    "TWO_FUNGI_BEASTS",
)
ACT1_ELITE_ENCOUNTERS = ("GREMLIN_NOB", "LAGAVULIN", "THREE_SENTRIES")
ACT1_BOSS_ENCOUNTERS = ("SLIME_BOSS", "THE_GUARDIAN", "HEXAGHOST")
ACT1_ENCOUNTERS = (
    ACT1_NORMAL_ENCOUNTERS + ACT1_ELITE_ENCOUNTERS + ACT1_BOSS_ENCOUNTERS
)

assert len(IRONCLAD_CARDS) == 75
assert len(ACT1_ENCOUNTERS) == 20
